// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: time.proto

#ifndef PROTOBUF_time_2eproto__INCLUDED
#define PROTOBUF_time_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_time_2eproto();
void protobuf_AssignDesc_time_2eproto();
void protobuf_ShutdownFile_time_2eproto();

class TimeInfo;

// ===================================================================

class TimeInfo : public ::google::protobuf::Message {
 public:
  TimeInfo();
  virtual ~TimeInfo();

  TimeInfo(const TimeInfo& from);

  inline TimeInfo& operator=(const TimeInfo& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TimeInfo& default_instance();

  void Swap(TimeInfo* other);

  // implements Message ----------------------------------------------

  TimeInfo* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const TimeInfo& from);
  void MergeFrom(const TimeInfo& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string tag = 1;
  inline bool has_tag() const;
  inline void clear_tag();
  static const int kTagFieldNumber = 1;
  inline const ::std::string& tag() const;
  inline void set_tag(const ::std::string& value);
  inline void set_tag(const char* value);
  inline void set_tag(const char* value, size_t size);
  inline ::std::string* mutable_tag();
  inline ::std::string* release_tag();
  inline void set_allocated_tag(::std::string* tag);

  // optional int64 sendTime = 2;
  inline bool has_sendtime() const;
  inline void clear_sendtime();
  static const int kSendTimeFieldNumber = 2;
  inline ::google::protobuf::int64 sendtime() const;
  inline void set_sendtime(::google::protobuf::int64 value);

  // optional int64 receiveTime = 3;
  inline bool has_receivetime() const;
  inline void clear_receivetime();
  static const int kReceiveTimeFieldNumber = 3;
  inline ::google::protobuf::int64 receivetime() const;
  inline void set_receivetime(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:TimeInfo)
 private:
  inline void set_has_tag();
  inline void clear_has_tag();
  inline void set_has_sendtime();
  inline void clear_has_sendtime();
  inline void set_has_receivetime();
  inline void clear_has_receivetime();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* tag_;
  ::google::protobuf::int64 sendtime_;
  ::google::protobuf::int64 receivetime_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_time_2eproto();
  friend void protobuf_AssignDesc_time_2eproto();
  friend void protobuf_ShutdownFile_time_2eproto();

  void InitAsDefaultInstance();
  static TimeInfo* default_instance_;
};
// ===================================================================


// ===================================================================

// TimeInfo

// optional string tag = 1;
inline bool TimeInfo::has_tag() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void TimeInfo::set_has_tag() {
  _has_bits_[0] |= 0x00000001u;
}
inline void TimeInfo::clear_has_tag() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void TimeInfo::clear_tag() {
  if (tag_ != &::google::protobuf::internal::kEmptyString) {
    tag_->clear();
  }
  clear_has_tag();
}
inline const ::std::string& TimeInfo::tag() const {
  return *tag_;
}
inline void TimeInfo::set_tag(const ::std::string& value) {
  set_has_tag();
  if (tag_ == &::google::protobuf::internal::kEmptyString) {
    tag_ = new ::std::string;
  }
  tag_->assign(value);
}
inline void TimeInfo::set_tag(const char* value) {
  set_has_tag();
  if (tag_ == &::google::protobuf::internal::kEmptyString) {
    tag_ = new ::std::string;
  }
  tag_->assign(value);
}
inline void TimeInfo::set_tag(const char* value, size_t size) {
  set_has_tag();
  if (tag_ == &::google::protobuf::internal::kEmptyString) {
    tag_ = new ::std::string;
  }
  tag_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* TimeInfo::mutable_tag() {
  set_has_tag();
  if (tag_ == &::google::protobuf::internal::kEmptyString) {
    tag_ = new ::std::string;
  }
  return tag_;
}
inline ::std::string* TimeInfo::release_tag() {
  clear_has_tag();
  if (tag_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = tag_;
    tag_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void TimeInfo::set_allocated_tag(::std::string* tag) {
  if (tag_ != &::google::protobuf::internal::kEmptyString) {
    delete tag_;
  }
  if (tag) {
    set_has_tag();
    tag_ = tag;
  } else {
    clear_has_tag();
    tag_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// optional int64 sendTime = 2;
inline bool TimeInfo::has_sendtime() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void TimeInfo::set_has_sendtime() {
  _has_bits_[0] |= 0x00000002u;
}
inline void TimeInfo::clear_has_sendtime() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void TimeInfo::clear_sendtime() {
  sendtime_ = GOOGLE_LONGLONG(0);
  clear_has_sendtime();
}
inline ::google::protobuf::int64 TimeInfo::sendtime() const {
  return sendtime_;
}
inline void TimeInfo::set_sendtime(::google::protobuf::int64 value) {
  set_has_sendtime();
  sendtime_ = value;
}

// optional int64 receiveTime = 3;
inline bool TimeInfo::has_receivetime() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void TimeInfo::set_has_receivetime() {
  _has_bits_[0] |= 0x00000004u;
}
inline void TimeInfo::clear_has_receivetime() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void TimeInfo::clear_receivetime() {
  receivetime_ = GOOGLE_LONGLONG(0);
  clear_has_receivetime();
}
inline ::google::protobuf::int64 TimeInfo::receivetime() const {
  return receivetime_;
}
inline void TimeInfo::set_receivetime(::google::protobuf::int64 value) {
  set_has_receivetime();
  receivetime_ = value;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_time_2eproto__INCLUDED
